# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build 1.16

on:
  push:
    branches: [ 1.16.5 ]
  pull_request:
    branches: [ 1.16.5 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.0-beta.4
      with:
        arguments: build
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
